# Используем официальный образ Golang для сборки
FROM golang:1.21 AS builder

RUN mkdir /app
# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем go.mod и go.sum
COPY go.mod go.sum ./

# Загружаем зависимости
RUN go mod download

# Копируем весь исходный код
COPY . .

# Собираем бинарник
RUN go build -o main .

# Используем минимальный образ для запуска
FROM alpine:latest

# Устанавливаем рабочую директорию
WORKDIR /root/

# Копируем собранный бинарник из builder-этапа
COPY --from=builder /app/main .

# Указываем команду по умолчанию
CMD ["./main"] 