// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/notification.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateNotificationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateNotificationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateNotificationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateNotificationRequestMultiError, or nil if none found.
func (m *CreateNotificationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateNotificationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for RequestId

	if len(errors) > 0 {
		return CreateNotificationRequestMultiError(errors)
	}

	return nil
}

// CreateNotificationRequestMultiError is an error wrapping multiple validation
// errors returned by CreateNotificationRequest.ValidateAll() if the
// designated constraints aren't met.
type CreateNotificationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateNotificationRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateNotificationRequestMultiError) AllErrors() []error { return m }

// CreateNotificationRequestValidationError is the validation error returned by
// CreateNotificationRequest.Validate if the designated constraints aren't met.
type CreateNotificationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateNotificationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateNotificationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateNotificationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateNotificationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateNotificationRequestValidationError) ErrorName() string {
	return "CreateNotificationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateNotificationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateNotificationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateNotificationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateNotificationRequestValidationError{}

// Validate checks the field values on CreateNotificationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateNotificationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateNotificationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateNotificationResponseMultiError, or nil if none found.
func (m *CreateNotificationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateNotificationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return CreateNotificationResponseMultiError(errors)
	}

	return nil
}

// CreateNotificationResponseMultiError is an error wrapping multiple
// validation errors returned by CreateNotificationResponse.ValidateAll() if
// the designated constraints aren't met.
type CreateNotificationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateNotificationResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateNotificationResponseMultiError) AllErrors() []error { return m }

// CreateNotificationResponseValidationError is the validation error returned
// by CreateNotificationResponse.Validate if the designated constraints aren't met.
type CreateNotificationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateNotificationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateNotificationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateNotificationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateNotificationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateNotificationResponseValidationError) ErrorName() string {
	return "CreateNotificationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateNotificationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateNotificationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateNotificationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateNotificationResponseValidationError{}

// Validate checks the field values on UpdateNotificationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateNotificationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateNotificationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateNotificationRequestMultiError, or nil if none found.
func (m *UpdateNotificationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateNotificationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for RequestId

	if len(errors) > 0 {
		return UpdateNotificationRequestMultiError(errors)
	}

	return nil
}

// UpdateNotificationRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateNotificationRequest.ValidateAll() if the
// designated constraints aren't met.
type UpdateNotificationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateNotificationRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateNotificationRequestMultiError) AllErrors() []error { return m }

// UpdateNotificationRequestValidationError is the validation error returned by
// UpdateNotificationRequest.Validate if the designated constraints aren't met.
type UpdateNotificationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateNotificationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateNotificationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateNotificationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateNotificationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateNotificationRequestValidationError) ErrorName() string {
	return "UpdateNotificationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateNotificationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateNotificationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateNotificationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateNotificationRequestValidationError{}

// Validate checks the field values on UpdateNotificationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateNotificationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateNotificationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateNotificationResponseMultiError, or nil if none found.
func (m *UpdateNotificationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateNotificationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return UpdateNotificationResponseMultiError(errors)
	}

	return nil
}

// UpdateNotificationResponseMultiError is an error wrapping multiple
// validation errors returned by UpdateNotificationResponse.ValidateAll() if
// the designated constraints aren't met.
type UpdateNotificationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateNotificationResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateNotificationResponseMultiError) AllErrors() []error { return m }

// UpdateNotificationResponseValidationError is the validation error returned
// by UpdateNotificationResponse.Validate if the designated constraints aren't met.
type UpdateNotificationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateNotificationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateNotificationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateNotificationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateNotificationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateNotificationResponseValidationError) ErrorName() string {
	return "UpdateNotificationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateNotificationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateNotificationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateNotificationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateNotificationResponseValidationError{}
